# Translations template for nova.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: nova\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-06-30 06:08+0000\n"
"PO-Revision-Date: 2014-06-24 16:11+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Spanish (http://www.transifex.com/projects/p/nova/language/"
"es/)\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: nova/compute/manager.py:1998
msgid "No more network or fixed IP to be allocated"
msgstr ""

#: nova/consoleauth/manager.py:84
#, python-format
msgid "Token: %(token)s failed to save into memcached."
msgstr ""

#: nova/consoleauth/manager.py:95
#, python-format
msgid "Instance: %(instance_uuid)s failed to save into memcached"
msgstr ""

#: nova/openstack/common/loopingcall.py:82
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr "la ejecución de tarea ha durado %s seg. más que el intervalo"

#: nova/openstack/common/network_utils.py:146
msgid "tcp_keepidle not available on your system"
msgstr ""

#: nova/openstack/common/network_utils.py:153
msgid "tcp_keepintvl not available on your system"
msgstr ""

#: nova/openstack/common/network_utils.py:160
msgid "tcp_keepknt not available on your system"
msgstr ""

#: nova/openstack/common/service.py:363
#, python-format
msgid "pid %d not in child list"
msgstr "El pid %d no está en la lista de hijos"

#: nova/openstack/common/db/sqlalchemy/session.py:506
#, python-format
msgid "Database server has gone away: %s"
msgstr ""

#: nova/openstack/common/db/sqlalchemy/session.py:559
msgid "Unable to detect effective SQL mode"
msgstr ""

#: nova/openstack/common/db/sqlalchemy/session.py:567
#, python-format
msgid ""
"MySQL SQL mode is '%s', consider enabling TRADITIONAL or STRICT_ALL_TABLES"
msgstr ""

#: nova/openstack/common/db/sqlalchemy/session.py:673
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr "La conexión SQL ha fallado. Quedan %s intentos."

#: nova/openstack/common/db/sqlalchemy/utils.py:97
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr "Id no está en sort_keys; ¿es sort_keys exclusivo?"

#: nova/scheduler/filters/core_filter.py:51
msgid "VCPUs not set; assuming CPU collection broken"
msgstr ""
"VCPU no establecidas; suponiendo que la colección de CPU se ha interrumpido"

#: nova/scheduler/filters/core_filter.py:92
#, python-format
msgid "Could not decode cpu_allocation_ratio: '%s'"
msgstr "No se puede decodificar cpu_allocation_ratio: '%s'"

#: nova/scheduler/filters/ram_filter.py:95
#, python-format
msgid "Could not decode ram_allocation_ratio: '%s'"
msgstr "No se puede decodificar ram_allocation_ratio: '%s'"

#: nova/virt/libvirt/driver.py:368
#, python-format
msgid "Invalid cachemode %(cache_mode)s specified for disk type %(disk_type)s."
msgstr ""
"Modalidad de caché %(cache_mode)s no válida especificada para el tipo de "
"disco %(disk_type)s."

#: nova/virt/libvirt/driver.py:606
#, python-format
msgid ""
"The libvirt driver is not tested on %(type)s/%(arch)s by the OpenStack "
"project and thus its quality can not be ensured. For more information, see: "
"https://wiki.openstack.org/wiki/HypervisorSupportMatrix"
msgstr ""
"El controlador libvirt no ha sido probado en %(type)s/%(arch)s por el "
"projecto de OpenStack  por lo cual su calidad no puede ser asegurada. Para "
"mas información, ver: https://wiki.openstack.org/wiki/HypervisorSupportMatrix"

#: nova/virt/libvirt/driver.py:656
#, python-format
msgid "URI %(uri)s does not support events: %(error)s"
msgstr "URI %(uri)s no soporta eventos: %(error)s"

#: nova/virt/libvirt/driver.py:672
#, python-format
msgid "URI %(uri)s does not support connection events: %(error)s"
msgstr "URI %(uri)s no soporta eventos de conexión: %(error)s"

#: nova/virt/libvirt/driver.py:865
msgid "Cannot destroy instance, operation time out"
msgstr ""
"No se puede destruir intsancia, tiempo de espera agotado para la operación"

#: nova/virt/libvirt/driver.py:971
msgid "Instance may be still running, destroy it again."
msgstr "Puede que la instancia aún se esté ejecutando, vuelva a destruirla."

#: nova/virt/libvirt/driver.py:1026
#, python-format
msgid "Ignoring Volume Error on vol %(vol_id)s during delete %(exc)s"
msgstr ""
"Ignorando Error de volumen en volumen %(vol_id)s durante la remocion %(exc)s"

#: nova/virt/libvirt/driver.py:1076
#, python-format
msgid "Volume %(disk)s possibly unsafe to remove, please clean up manually"
msgstr ""
"El volumen %(disk)s es posiblemente inseguro para remover, por favor "
"límpialo manualmente"

#: nova/virt/libvirt/driver.py:1357 nova/virt/libvirt/driver.py:1365
msgid "During detach_volume, instance disappeared."
msgstr "Durante detach_volume, la instancia ha desaparecido."

#: nova/virt/libvirt/driver.py:1410
msgid "During detach_interface, instance disappeared."
msgstr "Durante detach_interface, la instancia ha desaparecido."

#: nova/virt/libvirt/driver.py:1976
msgid "Failed to soft reboot instance. Trying hard reboot."
msgstr ""
"Fallo al reiniciar la instancia de manera suave. Intentando reinicio duro."

#: nova/virt/libvirt/driver.py:2537
#, python-format
msgid "Image %s not found on disk storage. Continue without injecting data"
msgstr ""
"La imagen %s no se ha encontrado en el almacenamiento de disco. Continuando "
"sin inyectar datos."

#: nova/virt/libvirt/driver.py:2700
msgid "File injection into a boot from volume instance is not supported"
msgstr ""
"La inyección de archivo al arranque desde la instancia del volumen no está "
"soportado."

#: nova/virt/libvirt/driver.py:2775
msgid "Instance disappeared while detaching a PCI device from it."
msgstr ""
"La instancia ha desaparecido mientras se removía el dispositivo PCI de ella."

#: nova/virt/libvirt/driver.py:2830
#, python-format
msgid "Cannot update service status on host: %s,since it is not registered."
msgstr ""
"No se puede actualizar el estado del servicio en el anfitrión: %s, ya que el "
"mismo no está registrado."

#: nova/virt/libvirt/driver.py:2833
#, python-format
msgid ""
"Cannot update service status on host: %s,due to an unexpected exception."
msgstr ""
"No se puede atualizar el estado del servicio en el anfitrión: %s, debido a "
"una excepción inesperada."

#: nova/virt/libvirt/driver.py:2861
#, python-format
msgid "URI %(uri)s does not support full set of host capabilities: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:3672
#, python-format
msgid "Timeout waiting for vif plugging callback for instance %(uuid)s"
msgstr ""
"Tiempo excedido para la llamada inversa de la conexión vif para la instancia "
"%(uuid)s"

#: nova/virt/libvirt/driver.py:3750
msgid ""
"Cannot get the number of cpu, because this function is not implemented for "
"this platform. "
msgstr ""
"No se puede obtener el número de CPU porque esta función no está "
"implementada para esta plataforma. "

#: nova/virt/libvirt/driver.py:3813
#, python-format
msgid "couldn't obtain the vpu count from domain id: %(id)s, exception: %(ex)s"
msgstr ""
"no se puede obtener el conteo de vpu del identificador del dominio: %(id)s, "
"excepción: %(ex)s"

#: nova/virt/libvirt/driver.py:4050
#, python-format
msgid "URI %(uri)s does not support listDevices: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4594
#, python-format
msgid "plug_vifs() failed %(cnt)d. Retry up to %(max_retry)d."
msgstr "plug_vifs() ha fallado %(cnt)d. Intentando hasta %(max_retry)d."

#: nova/virt/libvirt/driver.py:4727
#, python-format
msgid ""
"Error from libvirt while getting description of %(instance_name)s: [Error "
"Code %(error_code)s] %(ex)s"
msgstr ""
"Error de libvirt al obtener la descripción de %(instance_name)s: [Código de "
"error %(error_code)s] %(ex)s"

#: nova/virt/libvirt/driver.py:4805
#, python-format
msgid ""
"Periodic task is updating the host stat, it is trying to get disk "
"%(i_name)s, but disk file was removed by concurrent operations such as "
"resize."
msgstr ""
"La tarea periódica está actualizando las estadísticas del anfitrión, está "
"intentando obtener el disco %(i_name)s, pero el disco ha sido removido por "
"operaciones concurrentes como la modificación de tamaño."

#: nova/virt/libvirt/driver.py:4811
#, python-format
msgid ""
"Periodic task is updating the host stat, it is trying to get disk "
"%(i_name)s, but access is denied. It is most likely due to a VM that exists "
"on the compute node but is not managed by Nova."
msgstr ""

#: nova/virt/libvirt/firewall.py:49
msgid ""
"Libvirt module could not be loaded. NWFilterFirewall will not work correctly."
msgstr ""
"El módulo lLibvirt no se ha podido cargar. NWFilterFirewall no funcionará "
"correctamente."

#: nova/virt/libvirt/imagecache.py:318
#, python-format
msgid ""
"Instance %(instance)s is using a backing file %(backing)s which does not "
"appear in the image service"
msgstr ""
"La instancia %(instance)s utiliza un archivo de respaldo %(backing)s que no "
"aparece en el servicio de la imagen"

#: nova/virt/libvirt/imagecache.py:495
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): warning -- an absent base file is in use! "
"instances: %(instance_list)s"
msgstr ""
"%(id)s (%(base_file)s): aviso -- se está utilizando un archivo base ausente. "
"instancias: %(instance_list)s"

#: nova/virt/libvirt/imagecache.py:545
#, python-format
msgid "Unknown base file: %s"
msgstr "Archivo de base desconocido: %s "

#: nova/virt/libvirt/lvm.py:68
#, python-format
msgid ""
"Volume group %(vg)s will not be able to hold sparse volume %(lv)s. Virtual "
"volume size is %(size)db, but free space on volume group is only "
"%(free_space)db."
msgstr ""
"El grupo de volumen %(vg)s no podrá retener el volumen disperso %(lv)s. El "
"tamaño del volumen virtual es %(size)db, pero el espacio libre en el grupo "
"de volúmenes es solo %(free_space)db."

#: nova/virt/libvirt/utils.py:69 nova/virt/libvirt/utils.py:75
msgid "systool is not installed"
msgstr "systool no está instalado"

#: nova/virt/libvirt/utils.py:242
#, python-format
msgid "rbd remove %(name)s in pool %(pool)s failed"
msgstr "la remoción rbd de %(name)s en el conjunto %(pool)s ha fallado"

#: nova/virt/libvirt/vif.py:827
#, python-format
msgid ""
"VIF driver \"%s\" is marked as deprecated and will be removed in the Juno "
"release."
msgstr ""

#: nova/virt/libvirt/volume.py:132
#, python-format
msgid "Unknown content in connection_info/qos_specs: %s"
msgstr "Contenido desconocido en connection_info/qos_specs: %s"

#: nova/virt/libvirt/volume.py:294
#, python-format
msgid ""
"ISCSI volume not yet found at: %(disk_dev)s. Will rescan & retry.  Try "
"number: %(tries)s"
msgstr ""
"El volumen ISCSI aún no se ha encontrado en: %(disk_dev)s. Se volverá a "
"explorar y se reintentará. Número de intentos: %(tries)s"

#: nova/virt/libvirt/volume.py:361
#, python-format
msgid "Unable to delete volume device %s"
msgstr "Incapaz de eliminar el dispositivo de volumen %s"

#: nova/virt/libvirt/volume.py:372
#, python-format
msgid ""
"Failed to remove multipath device descriptor %(dev_mapper)s. Exception "
"message: %(msg)s"
msgstr ""
"Fallo al remover el descriptor del dispositivo multiruta %(dev_mapper)s. "
"Mensaje de excepción: %(msg)s"

#: nova/virt/libvirt/volume.py:694 nova/virt/libvirt/volume.py:843
#, python-format
msgid "%s is already mounted"
msgstr "%s ya está montado "

#: nova/virt/libvirt/volume.py:739
#, python-format
msgid "AoE volume not yet found at: %(aoedevpath)s. Try number: %(tries)s"
msgstr ""
"El volumen AoE aún no se ha encontrado en: %(aoedevpath)s. Número de "
"intentos: %(tries)s"

#: nova/virt/libvirt/volume.py:931
#, python-format
msgid ""
"Fibre volume not yet found at: %(mount_device)s. Will rescan & retry.  Try "
"number: %(tries)s"
msgstr ""
"El volumen de fibra aún no se ha encontrado en: %(mount_device)s. Se volverá "
"a explorar y se reintentará. Número de intentos: %(tries)s"

#: nova/virt/libvirt/volume.py:1033
msgid "Value required for 'scality_sofs_config'"
msgstr "Valor necesario para 'scality_sofs_config'"

#: nova/virt/libvirt/volume.py:1044
#, python-format
msgid "Cannot access 'scality_sofs_config': %s"
msgstr "No se puede acceder a 'scality_sofs_config': %s"

#: nova/virt/libvirt/volume.py:1050
msgid "Cannot execute /sbin/mount.sofs"
msgstr "No se puede ejecutar /sbin/mount.sofs"

#: nova/virt/libvirt/volume.py:1065
msgid "Cannot mount Scality SOFS, check syslog for errors"
msgstr "No se puede montar Scality SOFS, compruebe syslog por si hay errores"
